### ISSUE TITLE
[System Tests] RestartKafkaBrokers test is reporting an error many times

### ISSUE THREAD

**Issue by franvila** [kroxylicious/kroxylicious#1520]
**Describe the bug**
The RestartKafkaBrokers test is reporting an error because the broker is not restarted as expected, but it is out of scope the test.

**To Reproduce**
Run the RestartKafkaBrokers test

**Expected behavior**
The broker should be restarted successfully. If this is something that is happening a lot I'd suggest to be less restricted about checking if it is restarted successfully or not, we just want a broker to be removed and check that the messages are still being received.

**YAML files and logs**

```
io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [300000] milliseconds for [Pod] with name:[my-cluster-kafka-0] in namespace [kafka].

	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.waitUntilCondition(BaseOperation.java:946)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.waitUntilCondition(BaseOperation.java:98)
	at io.kroxylicious.systemtests.utils.KafkaUtils.restartBroker(KafkaUtils.java:126)
	at io.kroxylicious.systemtests.steps.KafkaSteps.restartKafkaBroker(KafkaSteps.java:85)
	at io.kroxylicious.systemtests.KroxyliciousST.restartKafkaBrokers(KroxyliciousST.java:96)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

[KroxyliciousST_restartKafkaBrokers_cluster_dump_2024_09_20_08_39_08.zip](https://github.com/user-attachments/files/17073198/KroxyliciousST_restartKafkaBrokers_cluster_dump_2024_09_20_08_39_08.zip)

**Additional context**

**Comment by k-wall** [comment]
> The broker should be restarted successfully. If this is something that is happening a lot I'd suggest to be less restricted

Surely, the broker should come back after it is restarted. If it doesn't something is wrong, no?

> io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [300000] milliseconds for [Pod] with name:[my-cluster-kafka-0] in namespace [kafka].

what's the state of the pod according to the kube client?  Looking at the logs you attach, the broker is running:

```
2024-09-20 08:34:24,385 INFO [BrokerLifecycleManager id=0] The broker has been unfenced. Transitioning from RECOVERY to RUNNING. (kafka.server.BrokerLifecycleManager) [broker-0-lifecycle-manager-event-handler]
```
