### ISSUE TITLE
SNI network k8s-example multiple java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by SamBarker** [kroxylicious/kroxylicious#1586]
### Discussed in https://github.com/kroxylicious/kroxylicious/discussions/1566

<div type='discussions-op-text'>

<sup>Originally posted by **Pavelsky89** November  1, 2024</sup>
Hi All,

I experimented with snirouting_tls example and I possibly found two issues with it

First issue is that when I run the example by following command from project root

`./scripts/run-example.sh kubernetes-examples/network-topologies/snirouting_tls`

at the end of minikube setup it should run post install script but it's unable to do so because it can't load common.sh using relative path, paths are probably broken, unless I am doing something wrong.

`kubernetes-examples/network-topologies/snirouting_tls/postinstall.sh: line 15: /<my-home>/kroxylicious/kubernetes-examples/network-topologies/snirouting_tls/../../scripts/common.sh: No such file or directory`

Anyway I ran the post script manually with success and it seems that the example is kinda working, but I got a lot of SSL handshake failures in proxy which results in producers/consumers losing connections. Stack trace from proxy in DEBUG mode

`2024-10-31 14:10:05 <epollEventLoopGroup-5-1> WARN  io.kroxylicious.proxy.internal.KafkaProxyFrontendHandler:363 - Connection to target cluster on my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093 failed with: null, closing inbound channel. Increase log level to DEBUG for stacktrace
java.nio.channels.ClosedChannelException: null
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1162) [netty-handler-4.1.114.Final.jar:4.1.114.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) [netty-transport-4.1.114.Final.jar:4.1.114.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) [netty-transport-4.1.114.Final.jar:4.1.114.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) [netty-transport-4.1.114.Final.jar:4.1.114.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1352) [netty-transport-4.1.114.Final.jar:4.1.114.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301) [netty-transport-4.1.114.Final.jar:4.1.114.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) [netty-transport-4.1.114.Final.jar:4.1.114.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:850) [netty-transport-4.1.114.Final.jar:4.1.114.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:811) [netty-transport-4.1.114.Final.jar:4.1.114.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) [netty-common-4.1.114.Final.jar:4.1.114.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) [netty-common-4.1.114.Final.jar:4.1.114.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-common-4.1.114.Final.jar:4.1.114.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:405) [netty-transport-classes-epoll-4.1.114.Final.jar:4.1.114.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.114.Final.jar:4.1.114.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.114.Final.jar:4.1.114.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.114.Final.jar:4.1.114.Final]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
	Suppressed: io.netty.handler.ssl.StacklessSSLHandshakeException: Connection closed while SSL/TLS handshake was in progress
		at io.netty.handler.ssl.SslHandler.channelInactive(Unknown Source) ~[netty-handler-4.1.114.Final.jar:4.1.114.Final]
`

Have anyone tried to run it and experienced similar?

</div>

**Comment by Pavelsky89** [comment]
Can be closed, issue was caused by too low resources assigned to proxy

**Comment by showuon** [comment]
Thanks for the update. Closing it now.
