### ISSUE TITLE
Header sniHostname null when talking directly to service in sni routing mode

### ISSUE THREAD

**Issue by Pavelsky89** [kroxylicious/kroxylicious#1683]
Hi kroxy Team ! 

**The bug (?)**

I am not sure if this is a bug or a feature, but following example setup for [k8s sni routing](https://github.com/kroxylicious/kroxylicious/tree/main/kubernetes-examples/network-topologies/snirouting_tls) we faced an issue that when we try to directly connect to service from within cluster instead of going through the ingress, every application fails to establish connection with the kafka. We used java and golang based apps, all of them have the same issue.

 Error on proxy side is as below
```
2024-12-17 12:04:32 \<epollEventLoopGroup-5-1\> WARN  io.netty.channel.DefaultChannelPipeline:1101 - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: failed to get the SslContext for null
	at io.netty.handler.ssl.SniHandler.onLookupComplete(SniHandler.java:158) ~[netty-handler-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.handler.ssl.AbstractSniHandler.onLookupComplete(AbstractSniHandler.java:191) ~[netty-handler-4.1.113.Final.jar:4.1.113.Final]
	at io.kroxylicious.proxy.internal.KafkaProxyInitializer$2.onLookupComplete(KafkaProxyInitializer.java:152) ~[kroxylicious-runtime-0.9.0.jar:?]
	at io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:222) ~[netty-handler-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.handler.ssl.SslClientHelloHandler.decode(SslClientHelloHandler.java:201) ~[netty-handler-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530) ~[netty-codec-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469) ~[netty-codec-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868) [netty-transport-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) [netty-transport-classes-epoll-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501) [netty-transport-classes-epoll-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) [netty-transport-classes-epoll-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.113.Final.jar:4.1.113.Final]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.util.concurrent.CompletionException: io.kroxylicious.proxy.internal.net.EndpointResolutionException: No channel bindings found for binding address: \<any\>, port: 443, sniHostname: \<none\>, tls: true
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:687) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:144) ~[?:?]
	at io.kroxylicious.proxy.internal.net.EndpointRegistry.resolve(EndpointRegistry.java:542) ~[kroxylicious-runtime-0.9.0.jar:?]
	at io.kroxylicious.proxy.internal.KafkaProxyInitializer.lambda$initTlsChannel$1(KafkaProxyInitializer.java:120) ~[kroxylicious-runtime-0.9.0.jar:?]
	at io.netty.handler.ssl.SniHandler.lookup(SniHandler.java:147) ~[netty-handler-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.handler.ssl.AbstractSniHandler.lookup(AbstractSniHandler.java:182) ~[netty-handler-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:220) ~[netty-handler-4.1.113.Final.jar:4.1.113.Final]
	... 18 more
**Caused by: io.kroxylicious.proxy.internal.net.EndpointResolutionException: No channel bindings found for binding address: \<any\>, port: 443, sniHostname: \<none\>, tls: true**
	at io.kroxylicious.proxy.internal.net.EndpointRegistry.buildEndpointResolutionException(EndpointRegistry.java:601) ~[kroxylicious-runtime-0.9.0.jar:?]
	at io.kroxylicious.proxy.internal.net.EndpointRegistry.lambda$resolve$30(EndpointRegistry.java:564) ~[kroxylicious-runtime-0.9.0.jar:?]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:144) ~[?:?]
	at io.kroxylicious.proxy.internal.net.EndpointRegistry.resolve(EndpointRegistry.java:542) ~[kroxylicious-runtime-0.9.0.jar:?]
	at io.kroxylicious.proxy.internal.KafkaProxyInitializer.lambda$initTlsChannel$1(KafkaProxyInitializer.java:120) ~[kroxylicious-runtime-0.9.0.jar:?]
	at io.netty.handler.ssl.SniHandler.lookup(SniHandler.java:147) ~[netty-handler-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.handler.ssl.AbstractSniHandler.lookup(AbstractSniHandler.java:182) ~[netty-handler-4.1.113.Final.jar:4.1.113.Final]
	at io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:220) ~[netty-handler-4.1.113.Final.jar:4.1.113.Final]
	... 18 more
```

**To Reproduce**
1. Configure strimzi kafka with listener settings like below

```yaml
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    - authentication:
        type: scram-sha-512
      name: tls
      port: 9093
      tls: true
      type: internal
      configuration:
        brokerCertChainAndKey:
          secretName: rootca
          certificate: tls.crt
          key: tls.key
```
2. Configure kroxylicious in sni routing mode, with target cluster pointing to kafka listener on port 9093
 ```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kroxylicious-config
  namespace: my-namespace
data:
  config.yaml: |
    adminHttp:
      endpoints:
        prometheus: {}
    micrometer:
    - type: "StandardBindersHook"
      config:
        binderNames:
          - "JvmGcMetrics"
          - "JvmHeapPressureMetrics"
          - "JvmInfoMetrics"
          - "JvmMemoryMetrics"
          - "JvmThreadMetrics"
          - "ProcessorMetrics"
          - "UptimeMetrics"
    virtualClusters:
      my-cluster-proxy:
        targetCluster:
          bootstrap_servers: mykafka-kafka-bootstrap.my-namespace.svc.cluster.local:9093
          tls:
            trust:
              storeFile: /opt/kroxylicious/server/jks/truststore.jks
              storePassword:
                passwordFile: /opt/kroxylicious/server/keystore-password/storePassword
              storeType: JKS
        clusterNetworkAddressConfigProvider:
          type: SniRoutingClusterNetworkAddressConfigProvider
          config:
            bootstrapAddress: mykafka-bootstrap-proxy.my-domain:443
            brokerAddressPattern: mykafka-kafka-proxy-$(nodeId).my-domain
        logNetwork: false
        logFrames: false
        tls:
          key:
            certificateFile: /opt/kroxylicious/server/cert/tls.crt
            privateKeyFile: /opt/kroxylicious/server/cert/tls.key
```
3. Deploy app producing records to strimzi on port 9093
4. Observe that it works
5. Deploy app producing records to proxy service on port 443
6. Observe that it fails with missing sni header

**Expected behavior**
Producing to kafka through proxy on port 443 works the same way as producing directly to kafka on port 9093

**Comment by k-wall** [comment]
Could you share your Kroxylicious configuration?

**Comment by robobario** [comment]
What does the in-cluster client configuration look like? What bootstrap/security settings are you using?

**Comment by robobario** [comment]
thanks, that's enough to reproduce.

Cranking up the log level by editing the deployment with:

```yaml
        env:
        - name: KROXYLICIOUS_ROOT_LOG_LEVEL
          value: DEBUG
```

I can see the error is preceded by:

```
2024-12-19 21:40:19 <epollEventLoopGroup-5-1> DEBUG io.netty.handler.ssl.SslClientHelloHandler - Unexpected client hello packet: 16030301bd010001b903038c4aa58f204952ebf71a1e58a7278ee3eacec10108af8b0bb2aff458274df624207a7fe9afe390b27f0e22498d4156063ebeec1729d9db9e5d66c723a3661e34ce003e130213011303c02cc02bcca9c030cca8c02f009fccaa009ec024c028c023c027006b0067c00ac014c009c01300390033009d009c003d003c0035002f00ff010001320000002600240000216b726f78796c6963696f75732d736572766963652e6b726f78796c6963696f7573000500050100000000000a00160014001d001700180019001e01000101010201030104000b00020100001100090007020004000000000017000000230000000d00220020040305030603080708080804080508060809080a080b04010501060103030301002b00050403040303002d00020101003200220020040305030603080708080804080508060809080a080b040105010601030303010033006b0069001d002018f766220d762ba9f06befe8808df96f6b881c8bd173fb3363bb418d4d0c9b5e00170041047dd2790e26181e6c03d93b0b6e4080bee3b44308ea7e1caaf4a0af378bbd9290dd7f752df4736bdec012b746c75586f783df6d4044b70d119edde7627c5be9f7
io.netty.handler.codec.DecoderException: failed to get the SslContext for kroxylicious-service.kroxylicious
	at io.netty.handler.ssl.SniHandler.onLookupComplete(SniHandler.java:158) ~[netty-handler-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.handler.ssl.AbstractSniHandler.onLookupComplete(AbstractSniHandler.java:191) ~[netty-handler-4.1.115.Final.jar:4.1.115.Final]
	at io.kroxylicious.proxy.internal.KafkaProxyInitializer$2.onLookupComplete(KafkaProxyInitializer.java:160) ~[kroxylicious-runtime-0.10.0-SNAPSHOT.jar:?]
	at io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:222) ~[netty-handler-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.handler.ssl.SslClientHelloHandler.decode(SslClientHelloHandler.java:178) ~[netty-handler-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530) ~[netty-codec-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469) ~[netty-codec-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:427) ~[netty-codec-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:394) ~[netty-codec-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:377) ~[netty-codec-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[netty-transport-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[netty-transport-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[netty-transport-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1352) ~[netty-transport-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301) ~[netty-transport-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[netty-transport-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:850) ~[netty-transport-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:811) ~[netty-transport-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:405) ~[netty-transport-classes-epoll-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.115.Final.jar:4.1.115.Final]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.util.concurrent.CompletionException: io.kroxylicious.proxy.internal.net.EndpointResolutionException: No channel bindings found for binding address: <any>, port: 9092, sniHostname: kroxylicious-service.kroxylicious, tls: true
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:687) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:144) ~[?:?]
	at io.kroxylicious.proxy.internal.net.EndpointRegistry.resolve(EndpointRegistry.java:542) ~[kroxylicious-runtime-0.10.0-SNAPSHOT.jar:?]
	at io.kroxylicious.proxy.internal.KafkaProxyInitializer.lambda$initTlsChannel$1(KafkaProxyInitializer.java:128) ~[kroxylicious-runtime-0.10.0-SNAPSHOT.jar:?]
	at io.netty.handler.ssl.SniHandler.lookup(SniHandler.java:147) ~[netty-handler-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.handler.ssl.AbstractSniHandler.lookup(AbstractSniHandler.java:182) ~[netty-handler-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:220) ~[netty-handler-4.1.115.Final.jar:4.1.115.Final]
	... 22 more
Caused by: io.kroxylicious.proxy.internal.net.EndpointResolutionException: No channel bindings found for binding address: <any>, port: 9092, sniHostname: kroxylicious-service.kroxylicious, tls: true
	at io.kroxylicious.proxy.internal.net.EndpointRegistry.buildEndpointResolutionException(EndpointRegistry.java:601) ~[kroxylicious-runtime-0.10.0-SNAPSHOT.jar:?]
	at io.kroxylicious.proxy.internal.net.EndpointRegistry.lambda$resolve$30(EndpointRegistry.java:564) ~[kroxylicious-runtime-0.10.0-SNAPSHOT.jar:?]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:144) ~[?:?]
	at io.kroxylicious.proxy.internal.net.EndpointRegistry.resolve(EndpointRegistry.java:542) ~[kroxylicious-runtime-0.10.0-SNAPSHOT.jar:?]
	at io.kroxylicious.proxy.internal.KafkaProxyInitializer.lambda$initTlsChannel$1(KafkaProxyInitializer.java:128) ~[kroxylicious-runtime-0.10.0-SNAPSHOT.jar:?]
	at io.netty.handler.ssl.SniHandler.lookup(SniHandler.java:147) ~[netty-handler-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.handler.ssl.AbstractSniHandler.lookup(AbstractSniHandler.java:182) ~[netty-handler-4.1.115.Final.jar:4.1.115.Final]
	at io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:220) ~[netty-handler-4.1.115.Final.jar:4.1.115.Final]
	... 22 more
```

So the trouble here is that the proxy is not aware of the `kroxylicious-service.kroxylicious` hostname (`kroxylicious-service.my-namespace.svc.cluster.local` in your case) and cannot map it to any virtual cluster's bootstrap or broker. The proxy is only aware of the configured hosts:

```
bootstrapAddress: mykafka-bootstrap-proxy.my-domain:443
brokerAddressPattern: mykafka-kafka-proxy-$(nodeId).my-domain
```

When a request comes in with an SSL Client Hello message containing `mykafka-bootstrap-proxy.my-domain` it can map it to the bootstrap of that virtual cluster. When a request comes in with `mykafka-kafka-proxy-1.my-domain` it can map it to broker 1 and so on.

The misleading log:
```
**Caused by: io.kroxylicious.proxy.internal.net.EndpointResolutionException: No channel bindings found for binding address: \<any\>, port: 443, sniHostname: \<none\>, tls: true**
```

is an unexpected side effect, the initial exception caused by the service hostname causes netty to try again with a `null` hostname [here](https://github.com/netty/netty/blob/2a58b07dbb22eeca2c3517c6393bd039614148dc/handler/src/main/java/io/netty/handler/ssl/SslClientHelloHandler.java#L201), which is the one that eventually bubbles up to the top level unhandled WARN logger.

So definitely something needs improving in the logging area, maybe for now we should log somewhere when that initial SNI mapping attempt fails at WARN too, to make it visible.

To access an SNI cluster with internal k8s services needs a different approach I think. You'd need a service for the bootstrap and N services for the brokers. And the certificates would have to be configured to work with the service hosts. We're currently thinking about how best to implement this in an operator.

**Comment by Pavelsky89** [comment]
Thank you for investigating this issue. 

Given the fact that sni mode works the way it works meaning that is creates only single service, is there any way how I can achieve successful communication with strimzi based kafka via service instead of ingress?

**Comment by robobario** [comment]
I've just put up a PR demonstrating using Kubernetes ClusterIP Services for in-cluster access.

In this example we create 4 services:
- my-cluster-proxy
- my-cluster-proxy-broker-0
- my-cluster-proxy-broker-1
- my-cluster-proxy-broker-2

And add them to the proxy certificate's SAN list

Where the broker ids in the service names must match the ids of the real target brokers. Then the proxy is configured with:
```yaml
virtualClusters:
  my-cluster-proxy:
    targetCluster:
      bootstrap_servers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093
      tls: .. snip tls config ..
    clusterNetworkAddressConfigProvider:
      type: SniRoutingClusterNetworkAddressConfigProvider
      config:
        bootstrapAddress: my-cluster-proxy.kroxylicious:9092
        brokerAddressPattern: my-cluster-proxy-broker-$(nodeId).kroxylicious
    ...
```

so that clients in the same k8s cluster can bootstrap with `my-cluster-proxy.kroxylicious:9092`

**Comment by Pavelsky89** [comment]
Thanks for the example, will try that out for sure and let you know how that goes

**Comment by Pavelsky89** [comment]
I had some time to test the example you provided, and I can confirm it solved my problem. 

Though on the other hand after that my external access via ingress stopped working, I guess it is because of the same reason now. The way how I solved it is by configuring two virtual clusters pointing to the same listener on the target cluster. One virtual cluster handles external traffic from ingress, the other internal traffic from within the kubernetes itself. I have not found info in documentation that this is supported scenario, but I see no reason why it should not be, if that is not the case let me know.

Other than that I think issue can be closed

Thanks for help !

**Comment by SamBarker** [comment]
Two virtual clusters pointing at the same target Kafka cluster or listener is absolutely supported!

Glad you've got things working.
