### ISSUE TITLE
Improve netty pipeline error handling

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#293]
In the event of error occuring during the pipeline, netty catches the exception and logs the error.  This works okay for the moment but we probably want to think about:

* error metrics
* ensuring the text of the error message includes sufficient detail to track the fault.

```
2023-04-28 13:11:18 WARN  io.netty.channel.DefaultChannelPipeline:1152 - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: failed to get the SslContext for null
	at io.netty.handler.ssl.SniHandler.onLookupComplete(SniHandler.java:132) ~[netty-handler-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.handler.ssl.AbstractSniHandler.onLookupComplete(AbstractSniHandler.java:182) ~[netty-handler-4.1.91.Final.jar:4.1.91.Final]
	at io.kroxylicious.proxy.internal.KafkaProxyInitializer$1.onLookupComplete(KafkaProxyInitializer.java:72) ~[classes/:?]
	at io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:190) ~[netty-handler-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.handler.ssl.SslClientHelloHandler.decode(SslClientHelloHandler.java:169) ~[netty-handler-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:426) ~[netty-codec-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:393) ~[netty-codec-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376) ~[netty-codec-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:295) ~[netty-transport-classes-kqueue-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
	at java.lang.Thread.run(Thread.java:1623) [?:?]
Caused by: java.lang.IllegalStateException: Virtual cluster VirtualCluster [targetCluster=TargetCluster [bootstrapServers=localhost:51240], clusterEndpointProvider=io.kroxylicious.proxy.internal.clusterendpointprovider.StaticClusterEndpointConfigProvider@6af609ea, keyStoreFile=Optional[/var/folders/5s/v5576rp175bf4vrf15mgvffm0000gn/T/kproxy12669093218868482025/kafka.keystore.jks], keyPassword=Optional[29015ed0335549ef91dae021bd08a92a], logNetwork=false, logFrames=false] does not provide SSL context
	at io.kroxylicious.proxy.internal.KafkaProxyInitializer.lambda$initChannel$0(KafkaProxyInitializer.java:64) ~[classes/:?]
	at io.netty.handler.ssl.SniHandler$AsyncMappingAdapter.map(SniHandler.java:191) ~[netty-handler-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.handler.ssl.SniHandler$AsyncMappingAdapter.map(SniHandler.java:180) ~[netty-handler-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.handler.ssl.SniHandler.lookup(SniHandler.java:121) ~[netty-handler-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.handler.ssl.AbstractSniHandler.lookup(AbstractSniHandler.java:173) ~[netty-handler-4.1.91.Final.jar:4.1.91.Final]
	at io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:188) ~[netty-handler-4.1.91.Final.jar:4.1.91.Final]
	... 22 more
```

We should have our own handlers and we should have metrics counting the errors.  Let's raise a separate issue.

_Originally posted by @k-wall in https://github.com/kroxylicious/kroxylicious/pull/279#discussion_r1180331645_

**Comment by k-wall** [comment]
Triage - we said we probably want to focus on error metrics.

**Comment by k-wall** [comment]
Replaced by #1853
