### ISSUE TITLE
"Attempted to register a meter with id" errors during integration tests

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#463]
_Please use this to only for bug reports_. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/kroxylicious/kroxylicious/discussions) or use the [community Slack](https://kroxylicious.slack.com) chat.

**Describe the bug**

Running the integration tests on main, I notice ERRORs like this being spewed out.  The messages don't seem to cause harm and the tests still pass. The noise is unpleasant. 

```
2023-07-18 13:04:10 ERROR io.kroxylicious.proxy.internal.MeterRegistries:62 - Attempted to register a meter with id MeterId{name='jvm.gc.pause', tags=[tag(a=b),tag(action=end of minor GC),tag(cause=G1 Humongous Allocation),tag(gc=G1 Young Generation)]} which is already registered but with a different set of tag names
java.lang.IllegalArgumentException: tags for id MeterId{name='jvm.gc.pause', tags=[tag(a=b),tag(action=end of minor GC),tag(cause=G1 Humongous Allocation),tag(gc=G1 Young Generation)]} differ from existing meters registered
	at io.kroxylicious.proxy.internal.MeterRegistries$1.accept(MeterRegistries.java:63)
	at io.micrometer.core.instrument.MeterRegistry.accept(MeterRegistry.java:646)
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:612)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:577)
	at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:323)
	at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:444)
	at io.micrometer.core.instrument.binder.jvm.JvmGcMetrics$GcMetricsNotificationListener.handleNotification(JvmGcMetrics.java:211)
	at java.management/sun.management.NotificationEmitterSupport.sendNotification(NotificationEmitterSupport.java:155)
	at jdk.management/com.sun.management.internal.GarbageCollectorExtImpl.createGCNotification(GarbageCollectorExtImpl.java:115)
```

**To Reproduce**
1. `mvn  verify -pl integrationtests`

**Expected behavior**
No MeterRegistry errors logged to console.

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

**Comment by k-wall** [comment]
The issue is there are notification listeners being left behind in the JMX layer.  Some MeterBinders (JvmGcMetrics) are autocloseable, so Kroxylicious ought to be respecting that lifecycle and closing the binders  as Kroxylicious shuts-down.

I think it should probably be reversing the registration of the meters and removing the meter registry.

The call to `Metrics.globalRegistry.clear();` makes be suspect that @robobario might have fought this battle before, so I'm going to let him comment.
