### ISSUE TITLE
Kroxylicious loops if filter that requires configuration is configured without a config object

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#530]
_Please use this to only for bug reports_. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/kroxylicious/kroxylicious/discussions) or use the [community Slack](https://kroxylicious.slack.com) chat.

**Describe the bug**

As a deployer, if I misconfigure a filter by failing to pass the config object, Kroxylicious loops tightly emitting an error message like the below.

```yaml
virtualClusters:
  demo:
    targetCluster:
      bootstrap_servers: localhost:9092
    clusterNetworkAddressConfigProvider:
      type: PortPerBroker
      config:
        bootstrapAddress: localhost:9192
    logNetwork: false
    logFrames: false
filters:
  - type: ProduceValidator
# omit the required config object.
```

```
2023-08-08 17:01:46 WARN  io.kroxylicious.proxy.internal.KafkaProxyFrontendHandler:408 - Netty caught exception from the frontend: Cannot invoke "io.kroxylicious.proxy.filter.schema.config.ValidationConfig.getRules()" because "config" is null
java.lang.NullPointerException: Cannot invoke "io.kroxylicious.proxy.filter.schema.config.ValidationConfig.getRules()" because "config" is null
	at io.kroxylicious.proxy.filter.schema.ProduceValidationFilterBuilder.build(ProduceValidationFilterBuilder.java:36) ~[classes/:?]
	at io.kroxylicious.proxy.filter.schema.ProduceRequestValidationFilterContributor.lambda$static$0(ProduceRequestValidationFilterContributor.java:21) ~[classes/:?]
	at io.kroxylicious.proxy.service.BaseContributor$InstanceBuilder.construct(BaseContributor.java:57) ~[classes/:?]
	at io.kroxylicious.proxy.service.BaseContributor.getInstance(BaseContributor.java:41) ~[classes/:?]
	at io.kroxylicious.proxy.internal.filter.FilterContributorManager.getFilter(FilterContributorManager.java:46) ~[classes/:?]
	at io.kroxylicious.proxy.bootstrap.FilterChainFactory.lambda$createFilters$0(FilterChainFactory.java:42) ~[classes/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
```

**To Reproduce**
1. Configuration any filter that expects configuration, but omit the config object.
2. Start kroxylicious up.

**Expected behavior**

The configuration is invalid.  Kroxylicious should fail once and shutdown.

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

**Comment by gracegrimwood** [comment]
Triaged 16/08/23 - @SamBarker looking into this

**Comment by SamBarker** [comment]
Fixed with https://github.com/kroxylicious/kroxylicious/pull/612 but apparently I missed the magic keyword in the PR
