### ISSUE TITLE
Kroxylicious fails "Unexpected api key: 84" when proxying Confluent Cloud and using the Kaf (sarama based) client

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious#822]
**Describe the bug**

```
2023-12-12 18:21:33 <epollEventLoopGroup-5-2> ERROR io.kroxylicious.proxy.internal.codec.KafkaRequestDecoder:55 - ChannelHandlerContext(requestDecoder, [id: 0x78da5426, L:/10.244.0.15:30192 - R:/10.244.0.1:10906]): Error in decoder
java.lang.IllegalArgumentException: Unexpected api key: 84
	at org.apache.kafka.common.protocol.ApiKeys.forId(ApiKeys.java:189) ~[kafka-clients-3.6.1.jar:?]
	at io.kroxylicious.proxy.internal.codec.KafkaRequestDecoder.decodeHeaderAndBody(KafkaRequestDecoder.java:46) ~[kroxylicious-runtime-0.4.0-SNAPSHOT.jar:?]
	at io.kroxylicious.proxy.internal.codec.KafkaMessageDecoder.decode(KafkaMessageDecoder.java:41) [kroxylicious-runtime-0.4.0-SNAPSHOT.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) [netty-codec-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) [netty-codec-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) [netty-codec-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [netty-transport-classes-epoll-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) [netty-transport-classes-epoll-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) [netty-transport-classes-epoll-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.101.Final.jar:4.1.101.Final]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
```

**To Reproduce**
1. Create a confluent cloud instance
2. Wire up kroxylicious to the cloud instance
```
        targetCluster:
          bootstrap_servers: pkc-xxxxx.europe-west2.gcp.confluent.cloud:9092
```
4. Configure kaf
5. Perform a `kaf topic list`

**Expected behavior**

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

**Comment by k-wall** [comment]
It appear to be failing to proxy the  authentication.

**Comment by k-wall** [comment]
The problem has two aspects:

1. Kaf is sending the unframed SASL authenticate.  There's no way to override that behaviour currently.
2. Kroxylicious can't handle an unframed SASL authenticate.  It tries to process the bytes as if they were a RPC, and falls flat.

**Comment by k-wall** [comment]
> The problem has two aspects:
> 
> 1. Kaf is sending the unframed SASL authenticate.  There's no way to override that behaviour currently. [birdayz/kaf@master...k-wall:kaf:enable-sasl-v1](https://github.com/birdayz/kaf/compare/master...k-wall:kaf:enable-sasl-v1)
> 2. Kroxylicious can't handle an unframed SASL authenticate.  It tries to process the bytes as if they were a RPC, and falls flat.

**Comment by k-wall** [comment]
As this is known to affect only kaf (sarama based), not a priority for 0.5.0.  Probably not high priority for 0.6.0.

**Comment by k-wall** [comment]
> Kaf is sending the unframed SASL authenticate. There's no way to override that behaviour currently. [birdayz/kaf@master...k-wall:kaf:enable-sasl-v1](https://github.com/birdayz/kaf/compare/master...k-wall:kaf:enable-sasl-v1) (edit: I've opened a PR to add the ability)

kaf 0.2.7 is released that includes this fix.

**Comment by robobario** [comment]
Just bumping since we hit this again, slightly different error message though, will post here for posterity:

```
2025-12-02 21:32:33 ERROR <multiThreadIoEventLoopGroup-5-12> io.kr.pr.in.co.KafkaRequestDecoder - ChannelHandlerContext(requestDecoder, [id: 0xfa0c44c0, L:/10.244.0.12:9292 - R:/10.244.0.9:59980]): Error in decoder
java.lang.IllegalArgumentException: Unexpected api key: 28204
	at org.apache.kafka.common.protocol.ApiKeys.forId(ApiKeys.java:209)
	at io.kroxylicious.proxy.internal.codec.KafkaRequestDecoder.readApiKey(KafkaRequestDecoder.java:140)
	at io.kroxylicious.proxy.internal.codec.KafkaRequestDecoder.decodeHeaderAndBody(KafkaRequestDecoder.java:57)
	at io.kroxylicious.proxy.internal.codec.KafkaMessageDecoder.readSingleFrame(KafkaMessageDecoder.java:67)
	at io.kroxylicious.proxy.internal.codec.KafkaMessageDecoder.validateRead(KafkaMessageDecoder.java:78)
	at io.kroxylicious.proxy.internal.codec.KafkaMessageDecoder.decode(KafkaMessageDecoder.java:51)
	at io.kroxylicious.proxy.internal.codec.KafkaRequestDecoder.decode(KafkaRequestDecoder.java:28)
```

This was trying to use SASL_PLAINTEXT with scram-sha-512. The exact error probably varies by frame length. As Keith mentioned above the workaround is to update `SASL.Version` to `1` in your `kaf` configuration.

I've asked [upstream](https://github.com/birdayz/kaf/issues/419) if they're interested in updated to a default version 1 to align with the Sarama default of version 1.

Sadly looks like Kafka 4.0.0+ ended up carrying the v0 handshake logic with the [KIP](https://cwiki.apache.org/confluence/display/KAFKA/KIP-896%3A+Remove+old+client+protocol+API+versions+in+Kafka+4.0) saying:

`SaslHandshake: none due to clients (kafka-python) - V0 per the baseline` and further confirmation [here](https://github.com/apache/kafka/pull/18221#issuecomment-2546644494).

And I tested `kaf` can use scram-sha-512 and v0 to connect to an apache kafka 4.1.0 cluster.

So it's still around, `kaf` is the only usage we've run into and the kip mentions `kafka-python`. Supporting SASL v0 would be a whole thing in the proxy since our SASL-interested filters would need to talk SASL without the Kafka framing. So a separate API? I think we should resist it as much as possible.

**Comment by k-wall** [comment]
> So it's still around, kaf is the only usage we've run into and the kip mentions kafka-python. Supporting SASL v0 would be a whole thing in the proxy since our SASL-interested filters would need to talk SASL without the Kafka framing. So a separate API? 

Yeah

> I think we should resist it as much as possible.

+1
