### ISSUE TITLE
EOF on Kafka Admin Client

### ISSUE THREAD

**Issue by michaelandrepearce** [kroxylicious/kroxylicious#983]
_Please use this to only for bug reports_. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/kroxylicious/kroxylicious/discussions) or use the [community Slack](https://kroxylicious.slack.com) chat.

**Describe the bug**
Keep getting EOF when doing simply Kafka Admin tasks like list topics, expected output would be the virtualised kafka topics list.

When pointing direct to kafka, no issues, repoint to kroxy, we get this issue.

**To Reproduce**
1. Configure kroxylicious like this ...

docker-compose.yaml:

version: '3'
networks:
  kroxy_network:
    driver: bridge
volumes:
  redpanda: null

services:
  zoo:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo

  kroxy:
    image: quay.io/kroxylicious/kroxylicious-developer:0.5.0-SNAPSHOT
    command:
      - "--config"
      - "/opt/kroxylicious/config/config.yaml"
    ports:
      - 9190:9190
      - 9292:9292
      - 9293:9293
      - 9294:9294
      - 9295:9295
    volumes:
      - ./config/config.yaml:/opt/kroxylicious/config/config.yaml
    networks:
      - kroxy_network
    depends_on:
      - kafka

config.yaml:

adminHttp:
  endpoints:
    prometheus: {}
filters:
  - type: MultiTenantTransformationFilterFactory
virtualClusters:
  demo:
    targetCluster:
      bootstrap_servers: kafka:9092
    clusterNetworkAddressConfigProvider:
      type: PortPerBrokerClusterNetworkAddressConfigProvider
      config:
        bootstrapAddress: localhost:9292
    logNetwork: false
    logFrames: true

3. Run command

(Java)

    public static void main(String[] args) throws Exception {
        Map<String, Object> props = new HashMap<>();
        props.put(AdminClientConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9292");

        AdminClient a = KafkaAdminClient.create(props);
        a.listTopics().namesToListings().get().entrySet().forEach(e ->{
            System.out.println(e.getValue() + " :: " + e.getValue().name() + " :: " + e.getValue().isInternal());
        });
    }

5. See error

07:03:24.832 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient -- [AdminClient clientId=adminclient-1] Initiating connection to node localhost:9292 (id: -1 rack: null) using address localhost/127.0.0.1
07:03:24.833 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.common.network.Selector -- [AdminClient clientId=adminclient-1] Created socket with SO_RCVBUF = 342972, SO_SNDBUF = 146988, SO_TIMEOUT = 0 to node -1
07:03:24.833 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient -- [AdminClient clientId=adminclient-1] Completed connection to node -1. Fetching API versions.
07:03:24.833 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient -- [AdminClient clientId=adminclient-1] Initiating API versions fetch from node -1.
07:03:24.833 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient -- [AdminClient clientId=adminclient-1] Sending API_VERSIONS request with header RequestHeader(apiKey=API_VERSIONS, apiVersion=3, clientId=adminclient-1, correlationId=5, headerVersion=2) and timeout 3600000 to node -1: ApiVersionsRequestData(clientSoftwareName='apache-kafka-java', clientSoftwareVersion='3.6.1')
07:03:24.846 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.common.network.Selector -- [AdminClient clientId=adminclient-1] Connection with localhost/127.0.0.1 (channelId=-1) disconnected
java.io.EOFException: null
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:86)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:571)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1381)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1312)
	at java.base/java.lang.Thread.run(Thread.java:1583)
07:03:24.846 [kafka-admin-client-thread | adminclient-1] INFO org.apache.kafka.clients.NetworkClient -- [AdminClient clientId=adminclient-1] Node -1 disconnected.
07:03:24.846 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient -- [AdminClient clientId=adminclient-1] Cancelled in-flight API_VERSIONS request with correlation id 5 due to node -1 being disconnected (elapsed time since creation: 13ms, elapsed time since send: 13ms, request timeout: 3600000ms): ApiVersionsRequestData(clientSoftwareName='apache-kafka-java', clientSoftwareVersion='3.6.1')

**Expected behavior**

List or topics to be returned instantly, and no EOF in logs.

**YAML files and logs**

Attach or copy paste your kroxylicious configuration YAML (with sensitive details
like broker address redacted).
Attach or copy and paste relevant logs.

**Additional context**

**Comment by k-wall** [comment]
@michaelandrepearce thanks for the detailed defect report.  I'll take a look soon.

**Comment by robobario** [comment]
Thanks for the report @michaelandrepearce

turning up the Kroxy logs with:
```
environment:
      KROXYLICIOUS_ROOT_LOG_LEVEL: "TRACE"
```

you see a loop like:
```
TRACE io.kroxylicious.proxy.internal.KafkaProxyFrontendHandler:328 - Outbound connect error, closing inbound channel
kroxy  | io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:9092
```

The cluster metadata we get back from upstream is advertised as 127.0.0.1 which we can't connect to.

```
Dispatching upstream METADATA response to filter BrokerAddressFilter@1909669762: DecodedResponseFrame(METADATA(12)v12, header=ResponseHeaderData(correlationId=1), body=MetadataResponseData(throttleTimeMs=0, brokers=[MetadataResponseBroker(nodeId=0, host='127.0.0.1', port=9092, rack=null)], clusterId='-pZO9H0-R2uaCQFE7-gkng', controllerId=0, topics=[], clusterAuthorizedOperations=-2147483648))
```

The advertised listeners for 9092 on Kafka needs to advertise itself as `kafka`, something addressable from the Kroxy container. Like:
```
-       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
+       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://kafka:9092,DOCKER://host.docker.internal:29092
```

Having this logging at trace is very quiet, we don't want a stack trace by default but it would be good to see a one line WARN for outbound connection errors.

**Comment by robobario** [comment]
The logs added should make this problem visible from 0.5.0
